### Login Request to retrieve a token - API GATEWAY
POST http://localhost:4004/auth/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password123"
}

> {% client.global.set("token",response.body.token) %}


Without Gateway

POST http://localhost:4005/login

